#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mtools
Version  : 4.0.18
Release  : 2
URL      : ftp://ftp.gnu.org/gnu/mtools/mtools-4.0.18.tar.gz
Source0  : ftp://ftp.gnu.org/gnu/mtools/mtools-4.0.18.tar.gz
Summary  : mtools, read/write/list/format DOS disks under Unix
Group    : Development/Tools
License  : GFDL-1.3 GPL-3.0 GPL-3.0+
Requires: mtools-bin
Requires: mtools-doc
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)
BuildRequires : texinfo

%description
Mtools is a collection of utilities to access MS-DOS disks from GNU
and Unix without mounting them. It supports long file names, OS/2 Xdf
disks, ZIP/JAZ disks and 2m disks (store up to 1992k on a high density
3 1/2 disk).

%package bin
Summary: bin components for the mtools package.
Group: Binaries

%description bin
bin components for the mtools package.


%package doc
Summary: doc components for the mtools package.
Group: Documentation

%description doc
doc components for the mtools package.


%package extras
Summary: extras components for the mtools package.
Group: Default

%description extras
extras components for the mtools package.


%prep
%setup -q -n mtools-4.0.18

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/floppyd
/usr/bin/amuFormat.sh
/usr/bin/floppyd_installtest
/usr/bin/lz
/usr/bin/mattrib
/usr/bin/mbadblocks
/usr/bin/mcat
/usr/bin/mcd
/usr/bin/mcheck
/usr/bin/mclasserase
/usr/bin/mcomp
/usr/bin/mcopy
/usr/bin/mdel
/usr/bin/mdeltree
/usr/bin/mdir
/usr/bin/mdu
/usr/bin/mformat
/usr/bin/minfo
/usr/bin/mkmanifest
/usr/bin/mlabel
/usr/bin/mmd
/usr/bin/mmount
/usr/bin/mmove
/usr/bin/mpartition
/usr/bin/mrd
/usr/bin/mren
/usr/bin/mshortname
/usr/bin/mshowfat
/usr/bin/mtools
/usr/bin/mtoolstest
/usr/bin/mtype
/usr/bin/mxtar
/usr/bin/mzip
/usr/bin/tgz
/usr/bin/uz

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*

%files extras
%defattr(-,root,root,-)
/usr/bin/floppyd
